package example;

/**
* example/cotesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Usuari/Documents/NetBeansProjects/CorbaCotesInterface/src/cotes.idl
* lunes 29 de abril de 2019 00H13' BOT
*/

public final class cotesHolder implements org.omg.CORBA.portable.Streamable
{
  public example.cotes value = null;

  public cotesHolder ()
  {
  }

  public cotesHolder (example.cotes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = example.cotesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    example.cotesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return example.cotesHelper.type ();
  }

}
