package example;


/**
* example/cotes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Usuari/Documents/NetBeansProjects/CorbaCotesInterface/src/cotes.idl
* lunes 29 de abril de 2019 00H13' BOT
*/

public interface cotes extends cotesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface cotes
