package example;


/**
* example/cotesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Usuari/Documents/NetBeansProjects/CorbaCotesInterface/src/cotes.idl
* lunes 29 de abril de 2019 00H13' BOT
*/

public interface cotesOperations 
{
  String pedientes (int idcliente);
  String pagar (String facturas);
} // interface cotesOperations
